/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { findAllFeedBackByBook } from '../fn/feed-back/find-all-feed-back-by-book';
import { FindAllFeedBackByBook$Params } from '../fn/feed-back/find-all-feed-back-by-book';
import { PageResponseFeedBackResponse } from '../models/page-response-feed-back-response';
import { saveFeedBack } from '../fn/feed-back/save-feed-back';
import { SaveFeedBack$Params } from '../fn/feed-back/save-feed-back';

@Injectable({ providedIn: 'root' })
export class FeedBackService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `saveFeedBack()` */
  static readonly SaveFeedBackPath = '/feedbacks';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `saveFeedBack()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  saveFeedBack$Response(params: SaveFeedBack$Params, context?: HttpContext): Promise<StrictHttpResponse<number>> {
    const obs = saveFeedBack(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `saveFeedBack$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  saveFeedBack(params: SaveFeedBack$Params, context?: HttpContext): Promise<number> {
    const resp = this.saveFeedBack$Response(params, context);
    return resp.then((r: StrictHttpResponse<number>): number => r.body);
  }

  /** Path part for operation `findAllFeedBackByBook()` */
  static readonly FindAllFeedBackByBookPath = '/feedbacks/book/{book-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findAllFeedBackByBook()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllFeedBackByBook$Response(params: FindAllFeedBackByBook$Params, context?: HttpContext): Promise<StrictHttpResponse<PageResponseFeedBackResponse>> {
    const obs = findAllFeedBackByBook(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findAllFeedBackByBook$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllFeedBackByBook(params: FindAllFeedBackByBook$Params, context?: HttpContext): Promise<PageResponseFeedBackResponse> {
    const resp = this.findAllFeedBackByBook$Response(params, context);
    return resp.then((r: StrictHttpResponse<PageResponseFeedBackResponse>): PageResponseFeedBackResponse => r.body);
  }

}
