/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AuthenticationRequest } from './models/authentication-request';
export type { AuthenticationResponse } from './models/authentication-response';
export type { BookRequest } from './models/book-request';
export type { BookResponse } from './models/book-response';
export type { BorrowedBookResponse } from './models/borrowed-book-response';
export type { FeedBackRequest } from './models/feed-back-request';
export type { FeedBackResponse } from './models/feed-back-response';
export type { PageResponseBookResponse } from './models/page-response-book-response';
export type { PageResponseBorrowedBookResponse } from './models/page-response-borrowed-book-response';
export type { PageResponseFeedBackResponse } from './models/page-response-feed-back-response';
export type { RegistirationRequest } from './models/registiration-request';
